services:
  rkllama:
    container_name: rkllama
    image: ghcr.io/notpunchnox/rkllama:main
    build: .
    privileged: true
    volumes:
      - /mnt/emmc/ws/rk/rkllama/models:/opt/rkllama/models
    ports:
      - "11432:8080"
    restart: unless-stopped
